# Generated by Django 5.0.7 on 2024-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='mountain',
            old_name='title',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='technology',
        ),
        migrations.AddField(
            model_name='mountain',
            name='difficulty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mountain',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mountain',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
