# Generated by Django 5.0.7 on 2024-08-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_rename_description_mountain_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='detail_image',
            field=models.FileField(blank=True, upload_to='mountain_images/'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='first_image',
            field=models.FileField(blank=True, upload_to='mountain_images/'),
        ),
    ]
