# Generated by Django 5.0.7 on 2024-08-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='type',
            new_name='sub_type',
        ),
    ]
